version: '3.8'

services:
  powershell-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: powershell-api
    ports:
      - "3000:3000"
    volumes:
      - ./scripts:/app/scripts
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OKTA_ISSUER=${OKTA_ISSUER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - CORS_ORIGIN=${CORS_ORIGIN}
    restart: unless-stopped
